---
- name: create override directory for icinga 2 service
  file:
    state: directory
    path: /etc/systemd/system/icinga2.service.d
    owner: root
    group: root
    mode: 755
  when: coredumps != "absent"
- name: set core dump file size to infinity
  ini_file:
    path: /etc/systemd/system/icinga2.service.d/override.conf
    owner: root
    group: root
    mode: 0644
    section: Service
    option: LimitCore
    value: infinity
    state: "{{ coredumps | default('present') }}"
  notify:
    - reload systemd
    - restart icinga2
